# -*- coding: utf-8 -*-
import json
import os

# Helper to create question object
def q(question, choices, answer):
    assert len(choices) == 4, f"Choice count must be 4: {question}"
    assert 0 <= answer <= 3, f"Answer index must be 0-3: {question}"
    assert len(set(choices)) == 4, f"Duplicate choices in: {question}"
    return {"q": question, "choices": choices, "answer": answer}

data = {
    "HTML": {
        "Easy": {
            "1": [ # HTML Easy Level 1 - Absolute Fundamentals
                q("What does HTML stand for?", ["HyperText Markup Language", "Home Tool Markup Language", "Hyperlinks Text Machine Language", "HighText Marking Language"], 0),
                q("Which HTML tag is used for the main largest heading?", ["<h6>", "<head>", "<h1>", "<heading>"], 2),
                q("Which tag is used to create a paragraph in HTML?", ["<p>", "<para>", "<text>", "<pg>"], 0),
                q("Which tag creates a clickable hyperlink?", ["<link>", "<a>", "<href>", "<url>"], 1),
                q("Which tag is used to display an image on a webpage?", ["<picture>", "<image>", "<src>", "<img>"], 3),
                q("Which tag creates a line break within a paragraph?", ["<lb>", "<br>", "<break>", "<newline>"], 1),
                q("Which tag creates a horizontal visible dividing line?", ["<hr>", "<line>", "<border>", "<divider>"], 0),
                q("All visible page content in HTML is placed inside which tag?", ["<head>", "<title>", "<body>", "<meta>"], 2),
            ],
            "2": [ # HTML Easy Level 2 - Text Formatting & Simple Lists
                q("Which HTML tag creates bold text without extra semantic emphasis?", ["<bold>", "<b>", "<bb>", "<fat>"], 1),
                q("Which HTML tag creates italicized text?", ["<i>", "<it>", "<italic>", "<slanted>"], 0),
                q("Which tag defines an unordered (bulleted) list?", ["<ol>", "<ul>", "<dl>", "<list>"], 1),
                q("Which tag defines an ordered (numbered) list?", ["<ol>", "<ul>", "<nl>", "<num>"], 0),
                q("Which tag is used for each item inside a list?", ["<item>", "<list>", "<li>", "<entry>"], 2),
                q("Which tag emphasizes text with semantic importance (rendered bold)?", ["<strong>", "<imp>", "<weight>", "<dark>"], 0),
                q("Which tag gives verbal stress emphasis to text (rendered italic)?", ["<stress>", "<em>", "<italics>", "<focus>"], 1),
                q("Which tag represents underlined text?", ["<u>", "<under>", "<ul>", "<line>"], 0),
            ],
            "3": [ # HTML Easy Level 3 - Tables & Page Containers
                q("Which tag is used to create a table in HTML?", ["<grid>", "<tab>", "<table>", "<data>"], 2),
                q("Which tag defines a row inside an HTML table?", ["<td>", "<tr>", "<th>", "<row>"], 1),
                q("Which tag defines standard data cell in a table?", ["<td>", "<tr>", "<th>", "<cell>"], 0),
                q("Which tag defines a header cell in a table?", ["<th>", "<td>", "<head>", "<hcell>"], 0),
                q("Which generic block-level container tag is used to group elements?", ["<span>", "<div>", "<group>", "<box>"], 1),
                q("Which generic inline container tag is used to style text fragments?", ["<div>", "<span>", "<inline>", "<txt>"], 1),
                q("Which tag defines the title of an HTML document shown in the browser tab?", ["<name>", "<header>", "<title>", "<caption>"], 2),
                q("Where should the <title> tag be placed in an HTML document?", ["Inside <head>", "Inside <body>", "Inside <footer>", "After </html>"], 0),
            ],
            "4": [ # HTML Easy Level 4 - Basic Forms & User Input
                q("Which tag is used to create an interactive user form?", ["<form>", "<input>", "<submit>", "<survey>"], 0),
                q("Which tag creates an input field for user entry?", ["<entry>", "<input>", "<box>", "<text>"], 1),
                q("Which input type is used for typing a single-line text string?", ['type="text"', 'type="string"', 'type="input"', 'type="char"'], 0),
                q("Which input type hides entered characters with dots for passwords?", ['type="secret"', 'type="hidden"', 'type="password"', 'type="secure"'], 2),
                q("Which input type creates a square box that can be toggled on/off?", ['type="radio"', 'type="check"', 'type="checkbox"', 'type="box"'], 2),
                q("Which input type creates a circular choice where only one can be selected?", ['type="circle"', 'type="radio"', 'type="option"', 'type="dot"'], 1),
                q("Which tag creates a clickable button on an HTML page?", ["<btn>", "<button>", "<press>", "<click>"], 1),
                q("Which tag provides a text description for a form input element?", ["<label>", "<desc>", "<info>", "<name>"], 0),
            ],
            "5": [ # HTML Easy Level 5 - Attributes & Basic Links
                q("Which attribute specifies the URL destination of an <a> link?", ["src", "href", "link", "target"], 1),
                q("Which attribute specifies the image file path in an <img> tag?", ["src", "href", "url", "path"], 0),
                q("Which attribute provides alternative text if an image cannot load?", ["title", "alt", "desc", "src"], 1),
                q("Which target value opens a link in a new browser tab?", ['target="_new"', 'target="_blank"', 'target="_open"', 'target="_window"'], 1),
                q("Which attribute adds hover tooltip text to almost any HTML element?", ["tooltip", "title", "hint", "hover"], 1),
                q("Which tag creates a dropdown selection list in a form?", ["<list>", "<dropdown>", "<select>", "<menu>"], 2),
                q("Which tag defines each choice inside a <select> dropdown?", ["<option>", "<item>", "<li>", "<choice>"], 0),
                q("Which declaration must be the very first line of every modern HTML5 document?", ["<!DOCTYPE html>", "<html 5>", "<doctype modern>", "<?xml html>"], 0),
            ]
        },
        "Medium": {
            "1": [ # HTML Medium Level 1 - Semantic Layout Elements
                q("Which semantic tag represents navigation links for a website?", ["<menu>", "<nav>", "<links>", "<navbar>"], 1),
                q("Which semantic tag represents the introductory banner or header of a page?", ["<header>", "<top>", "<head>", "<banner>"], 0),
                q("Which semantic tag represents the bottom footer of a page?", ["<bottom>", "<base>", "<footer>", "<end>"], 2),
                q("Which semantic tag represents self-contained, independent article content?", ["<article>", "<section>", "<div>", "<entry>"], 0),
                q("Which semantic tag defines a generic distinct thematic section of content?", ["<group>", "<section>", "<part>", "<block>"], 1),
                q("Which semantic tag is best for sidebar or related supplementary content?", ["<aside>", "<sidebar>", "<extra>", "<subcontent>"], 0),
                q("Which semantic tag represents the central unique content of the page?", ["<main>", "<body>", "<content>", "<center>"], 0),
                q("Why is semantic HTML important for websites?", ["It makes pages look colorful automatically", "It provides meaning for search engines and screen readers", "It replaces the need for CSS", "It compiles HTML into binary"], 1),
            ],
            "2": [ # HTML Medium Level 2 - Form Attributes & Validation
                q("Which attribute shows ghost guidance text inside an input before the user types?", ["hint", "placeholder", "guide", "default"], 1),
                q("Which attribute prevents form submission if an input field is empty?", ["must", "required", "validate", "locked"], 1),
                q("Which attribute makes an input field non-editable but still readable?", ["readonly", "disabled", "frozen", "static"], 0),
                q("Which attribute grays out an input field and ignores user interaction completely?", ["disabled", "blocked", "inactive", "stop"], 0),
                q("Which form method sends sensitive form data securely in the HTTP request body?", ['method="GET"', 'method="POST"', 'method="SEND"', 'method="BODY"'], 1),
                q("Which form method appends entered data directly to the URL string?", ['method="POST"', 'method="GET"', 'method="URL"', 'method="FETCH"'], 1),
                q("Which input type submits the entire form to the server?", ['type="submit"', 'type="send"', 'type="finish"', 'type="post"'], 0),
                q("Which input type resets all form fields back to their initial values?", ['type="clear"', 'type="reset"', 'type="clean"', 'type="undo"'], 1),
            ],
            "3": [ # HTML Medium Level 3 - Advanced Table Structures
                q("Which attribute makes a table cell span across multiple columns horizontally?", ["colspan", "rowspan", "colwidth", "span"], 0),
                q("Which attribute makes a table cell stretch down across multiple rows vertically?", ["rowspan", "colspan", "rowheight", "extend"], 0),
                q("Which tag groups the header rows in an HTML table?", ["<thead>", "<thgroup>", "<caption>", "<header>"], 0),
                q("Which tag groups the main body data rows in a table?", ["<tbody>", "<content>", "<rows>", "<tdata>"], 0),
                q("Which tag groups the summary footer rows in a table?", ["<tfoot>", "<tbase>", "<tbottom>", "<summary>"], 0),
                q("Which tag adds a visible descriptive title caption directly above a table?", ["<caption>", "<title>", "<heading>", "<label>"], 0),
                q("What is the default text styling of a <th> table header cell?", ["Bold and centered", "Italic and left-aligned", "Underlined", "Gray and small"], 0),
                q("Which attribute is used to define an identifier that must be unique on the entire page?", ["class", "id", "name", "tag"], 1),
            ],
            "4": [ # HTML Medium Level 4 - Document Head, Metadata & Linking
                q("Which tag links an external CSS stylesheet to an HTML document?", ["<script>", "<style>", "<link>", "<css>"], 2),
                q("What should the rel attribute be when linking a stylesheet with <link>?", ['rel="style"', 'rel="stylesheet"', 'rel="css"', 'rel="design"'], 1),
                q("Which meta tag ensures proper responsive scaling on mobile phone screens?", ['<meta name="viewport" ...>', '<meta name="mobile" ...>', '<meta name="screen" ...>', '<meta name="scale" ...>'], 0),
                q("Which meta attribute specifies the character encoding (standard UTF-8)?", ['charset="UTF-8"', 'encoding="UTF-8"', 'code="UTF-8"', 'type="UTF-8"'], 0),
                q("Which tag is used to write embedded JavaScript directly inside an HTML file?", ["<script>", "<js>", "<javascript>", "<code>"], 0),
                q("Which tag allows writing embedded CSS rules directly within an HTML file?", ["<css>", "<style>", "<design>", "<format>"], 1),
                q("Which tag specifies the base URL for all relative URLs in a document?", ["<base>", "<root>", "<url>", "<source>"], 0),
                q("Which tag is used inside <head> to provide page keywords and author info?", ["<meta>", "<info>", "<data>", "<tag>"], 0),
            ],
            "5": [ # HTML Medium Level 5 - Multimedia & Embedded Elements
                q("Which HTML5 tag is used to embed an audio player?", ["<sound>", "<audio>", "<music>", "<player>"], 1),
                q("Which HTML5 tag is used to embed video content natively without plugins?", ["<movie>", "<video>", "<media>", "<film>"], 1),
                q("Which boolean attribute displays play, pause, and volume controls on <video>?", ["controls", "interface", "panel", "player"], 0),
                q("Which attribute causes an audio or video file to start playing as soon as loaded?", ["play", "autoplay", "instant", "start"], 1),
                q("Which attribute causes audio or video to replay automatically from the beginning?", ["loop", "repeat", "cycle", "again"], 0),
                q("Which tag embeds another webpage inside the current webpage?", ["<iframe>", "<embed>", "<window>", "<page>"], 0),
                q("Which tag provides alternative media file sources inside <video> or <audio>?", ["<source>", "<src>", "<alt>", "<item>"], 0),
                q("Which tag pairs an illustration image with its explanatory caption?", ["<figure> with <figcaption>", "<picture> with <desc>", "<image> with <text>", "<photo> with <label>"], 0),
            ]
        },
        "Hard": {
            "1": [ # HTML Hard Level 1 - Specialized HTML5 Input Types
                q("Which input type validates that the entered text matches email address syntax?", ['type="email"', 'type="mail"', 'type="address"', 'type="webmail"'], 0),
                q("Which input type presents a calendar picker for selecting a date?", ['type="date"', 'type="calendar"', 'type="day"', 'type="time"'], 0),
                q("Which input type restricts user typing to numbers and shows step arrows?", ['type="number"', 'type="digits"', 'type="numeric"', 'type="count"'], 0),
                q("Which input type displays a horizontal slider control for selecting a value in a range?", ['type="slider"', 'type="range"', 'type="meter"', 'type="bar"'], 1),
                q("Which input type brings up a native system color picker palette?", ['type="color"', 'type="palette"', 'type="rgb"', 'type="paint"'], 0),
                q("Which attribute specifies a regular expression pattern for input validation?", ["pattern", "regex", "validate", "match"], 0),
                q("Which attributes set the minimum and maximum numeric boundaries on a number input?", ["min and max", "low and high", "start and end", "floor and ceil"], 0),
                q("Which attribute specifies the increment step size for a numeric or range input?", ["step", "increment", "rate", "by"], 0),
            ],
            "2": [ # HTML Hard Level 2 - Advanced Form Controls
                q("Which tag creates a multi-line resizable text entry area?", ["<textarea>", '<input type="multiline">', "<textblock>", "<editor>"], 0),
                q("Which tag groups related form controls with a visible border around them?", ["<fieldset>", "<formgroup>", "<section>", "<borderbox>"], 0),
                q("Which tag provides a caption title for a <fieldset> grouping?", ["<legend>", "<caption>", "<title>", "<heading>"], 0),
                q("Which tag provides predefined autocomplete suggestions for an <input> field?", ["<datalist>", "<options>", "<autocomplete>", "<suggestions>"], 0),
                q("How do you connect an <input> to a <datalist> element?", ["Using the list attribute on the input", "Using the href attribute", "Using class attribute", "Using for attribute"], 0),
                q("Which tag represents the completion progress of a task with a progress bar?", ["<progress>", "<meter>", "<bar>", "<status>"], 0),
                q("Which tag represents a scalar measurement within a known range (like disk usage)?", ["<meter>", "<progress>", "<range>", "<gauge>"], 0),
                q("Which attribute allows users to select multiple options from a <select> list?", ["multiple", "many", "all", "multiselect"], 0),
            ],
            "3": [ # HTML Hard Level 3 - Interactive & Modern Elements
                q("Which HTML5 tag creates an interactive toggle disclosure widget?", ["<details>", "<accordion>", "<toggle>", "<collapse>"], 0),
                q("Which tag defines the clickable visible heading inside a <details> widget?", ["<summary>", "<header>", "<title>", "<label>"], 0),
                q("Which prefix is used to store custom data attributes on HTML elements for JavaScript?", ["data-*", "custom-*", "user-*", "js-*"], 0),
                q("Which HTML tag holds inert markup that is not rendered until cloned by JavaScript?", ["<template>", "<hidden>", "<cache>", "<ghost>"], 0),
                q("Which attribute tells the browser to defer JavaScript execution until after parsing?", ["defer", "async", "wait", "delay"], 0),
                q("Which attribute tells the browser to execute JavaScript asynchronously as soon as downloaded?", ["async", "defer", "fast", "parallel"], 0),
                q("Which attribute on a <script> tag prevents it from running if the script hash does not match (SRI)?", ["integrity", "security", "checksum", "hash"], 0),
                q("Which attribute controls whether browser spellchecking is enabled on an editable element?", ["spellcheck", "autocorrect", "grammar", "spelling"], 0),
            ],
            "4": [ # HTML Hard Level 4 - Accessibility (a11y) & Screen Readers
                q("What does ARIA stand for in web accessibility?", ["Accessible Rich Internet Applications", "Automated Reading Interface Audio", "Applied Responsive Internet Access", "Advanced Reader Interaction API"], 0),
                q("What attribute provides an explicit accessibility label if text is not visible?", ["aria-label", "alt-text", "screen-title", "reader-desc"], 0),
                q("Which attribute indicates whether an accordion or popup menu is currently open?", ["aria-expanded", "aria-open", "aria-active", "aria-show"], 0),
                q("Which attribute on an element completely hides it from assistive screen readers?", ['aria-hidden="true"', 'hidden="screen"', 'role="none"', 'style="a11y:false"'], 0),
                q("Why should form inputs always have an associated <label for='...'>?", ["It allows screen readers to announce the field and enlarges clickable area", "It makes CSS load faster", "It reduces HTML file size", "It encrypts the field values"], 0),
                q("Which role attribute specifies that a generic div acts as a clickable button?", ['role="button"', 'role="click"', 'role="interactive"', 'role="press"'], 0),
                q("Which attribute controls the tab order navigation of elements via keyboard?", ["tabindex", "taborder", "keyboardindex", "navorder"], 0),
                q("What does tabindex='0' do to an element?", ["Puts it in normal sequential keyboard tab order", "Removes it from tab navigation", "Makes it always focused first", "Locks keyboard input"], 0),
            ],
            "5": [ # HTML Hard Level 5 - SEO, Security & Standards
                q("Which rel attribute value prevents target='_blank' security vulnerabilities (tabnabbing)?", ['rel="noopener noreferrer"', 'rel="secure"', 'rel="nofollow"', 'rel="safe"'], 0),
                q("Which rel attribute value tells search engines not to pass ranking credit to an external link?", ['rel="nofollow"', 'rel="noindex"', 'rel="external"', 'rel="none"'], 0),
                q("Which meta tag instructs search engines not to index a specific web page?", ['<meta name="robots" content="noindex">', '<meta name="seo" content="stop">', '<meta name="google" content="block">', '<meta name="search" content="hidden">'], 0),
                q("What is the canonical tag used for in HTML head?", ["Specifies the preferred master URL to prevent duplicate content SEO penalties", "Forces HTTPS connections", "Compiles JavaScript", "Sets the primary page font"], 0),
                q("Which attribute makes any HTML element editable by the user in the browser?", ['contenteditable="true"', 'editable="yes"', 'modify="true"', 'type="editable"'], 0),
                q("What is the purpose of Open Graph meta tags (og:title, og:image)?", ["Customize previews when a link is shared on social media and messaging apps", "Format 3D graphics in HTML", "Connect to SQL databases", "Cache CSS files locally"], 0),
                q("Which attribute in an <img> tag tells the browser to defer loading until near viewport?", ['loading="lazy"', 'defer="image"', 'fetch="later"', 'wait="scroll"'], 0),
                q("Which element is used to render 2D/3D hardware-accelerated shapes via JavaScript?", ["<canvas>", "<svg>", "<paint>", "<render>"], 0),
            ]
        }
    },
    "CSS": {
        "Easy": {
            "1": [ # CSS Easy Level 1 - Introduction & Selectors
                q("What does CSS stand for?", ["Cascading Style Sheets", "Creative Style System", "Computer Styling Syntax", "Colorful Sheet Styles"], 0),
                q("Which character is used to select an HTML element by its class name?", [". (dot)", "# (hash)", "* (asterisk)", "@ (at)"], 0),
                q("Which character is used to select an HTML element by its unique ID?", ["# (hash)", ". (dot)", "& (ampersand)", "$ (dollar)"], 0),
                q("How do you write a comment in CSS?", ["/* comment */", "// comment", "<!-- comment -->", "' comment"], 0),
                q("Which CSS property changes the text color of an element?", ["color", "font-color", "text-color", "foreground"], 0),
                q("Which CSS property changes the background color of an element?", ["background-color", "bgcolor", "color-background", "canvas-color"], 0),
                q("In CSS, every property declaration must end with which punctuation mark?", ["; (semicolon)", ": (colon)", ". (period)", ", (comma)"], 0),
                q("Which selector targets every single element on the entire web page?", ["* (universal selector)", "all", "body", "html"], 0),
            ],
            "2": [ # CSS Easy Level 2 - Colors & Backgrounds
                q("Which of the following is a valid hexadecimal color for white?", ["#FFFFFF", "#000000", "#123456", "#FFF000"], 0),
                q("Which of the following represents pure red in RGB syntax?", ["rgb(255, 0, 0)", "rgb(0, 255, 0)", "rgb(0, 0, 255)", "rgb(100, 100, 100)"], 0),
                q("What does the 'a' stand for in rgba(255, 0, 0, 0.5)?", ["Alpha (transparency / opacity)", "Angle", "Area", "Accent"], 0),
                q("Which property sets a picture as the background of an element?", ["background-image: url('pic.jpg');", "image-background: 'pic.jpg';", "bg-pic: url('pic.jpg');", "wallpaper: 'pic.jpg';"], 0),
                q("Which property prevents a background image from repeating across the screen?", ["background-repeat: no-repeat;", "repeat: none;", "background-tile: off;", "image-repeat: false;"], 0),
                q("Which color name represents the total absence of color in hex?", ["#000000 (black)", "#FFFFFF", "#AAAAAA", "#CCCCCC"], 0),
                q("Which property makes a background image stretch to cover the entire container?", ["background-size: cover;", "background-stretch: full;", "image-size: 100%;", "background-fit: fill;"], 0),
                q("Which property centers a background image within its container?", ["background-position: center;", "image-align: center;", "background-align: middle;", "bg-center: true;"], 0),
            ],
            "3": [ # CSS Easy Level 3 - Text & Fonts
                q("Which CSS property changes the size of the text?", ["font-size", "text-size", "font-height", "size"], 0),
                q("Which CSS property specifies the font family (like Arial or Roboto)?", ["font-family", "font-name", "typeface", "text-font"], 0),
                q("Which CSS property aligns text to the left, center, or right?", ["text-align", "align-text", "text-position", "horizontal-align"], 0),
                q("Which CSS property makes text bold in styling?", ["font-weight: bold;", "text-bold: true;", "font-style: bold;", "weight: heavy;"], 0),
                q("Which CSS property makes text italic in styling?", ["font-style: italic;", "font-weight: italic;", "text-italic: true;", "style: slanted;"], 0),
                q("Which property removes underlines from hyperlinks (<a> tags)?", ["text-decoration: none;", "underline: false;", "link-style: none;", "text-line: off;"], 0),
                q("Which property converts all letters to uppercase or lowercase?", ["text-transform", "letter-case", "text-convert", "font-case"], 0),
                q("Which property sets the vertical spacing between lines of text?", ["line-height", "text-spacing", "line-gap", "font-leading"], 0),
            ],
            "4": [ # CSS Easy Level 4 - Box Model Basics
                q("Which part of the CSS box model is the space between the content and the border?", ["padding", "margin", "border", "outline"], 0),
                q("Which part of the CSS box model is the space outside the border between elements?", ["margin", "padding", "content", "inset"], 0),
                q("Which property adds a solid border around an element?", ["border: 1px solid black;", "outline-style: solid;", "border-draw: 1px black;", "box-border: 1px;"], 0),
                q("Which property rounds the sharp rectangular corners of an element into curves?", ["border-radius", "corner-curve", "box-round", "border-curve"], 0),
                q("If you set 'margin: 10px 20px;', what does 10px represent?", ["Top and bottom margin", "Left and right margin", "All four sides", "Only top margin"], 0),
                q("If you write 'padding: 10px;', which sides receive 10px of padding?", ["All four sides (top, right, bottom, left)", "Only top", "Only left and right", "Only bottom"], 0),
                q("Which property creates a circular avatar from a square image?", ["border-radius: 50%;", "corner-circle: true;", "round: circle;", "shape: 100%;"], 0),
                q("Which property sets only the top spacing outside an element?", ["margin-top", "padding-top", "top-spacing", "outer-top"], 0),
            ],
            "5": [ # CSS Easy Level 5 - Dimensions & Sizing
                q("Which CSS property controls the horizontal width of an element?", ["width", "height", "size-x", "length"], 0),
                q("Which CSS property controls the vertical height of an element?", ["height", "width", "size-y", "tallness"], 0),
                q("Which value centers a block element horizontally when width is set?", ["margin: 0 auto;", "align: center;", "padding: auto;", "float: center;"], 0),
                q("Which unit is an absolute fixed pixel measurement on screens?", ["px", "%", "em", "vh"], 0),
                q("Which unit sizes an element relative to the width of its parent container?", ["%", "px", "cm", "pt"], 0),
                q("Which property sets the maximum width an element is allowed to expand to?", ["max-width", "width-limit", "limit-x", "bound-width"], 0),
                q("Which property sets the minimum height an element can shrink to?", ["min-height", "height-floor", "limit-height", "low-height"], 0),
                q("Which property hides content that spills outside its container box?", ["overflow: hidden;", "spill: none;", "content: clipped;", "box-overflow: cut;"], 0),
            ]
        },
        "Medium": {
            "1": [ # CSS Medium Level 1 - Display & Visibility
                q("Which display value makes elements stack vertically and take the full width available?", ["display: block;", "display: inline;", "display: flex;", "display: none;"], 0),
                q("Which display value allows elements to sit side-by-side without line breaks?", ["display: inline;", "display: block;", "display: table;", "display: stack;"], 0),
                q("Which display value combines inline flow with the ability to set width and height?", ["display: inline-block;", "display: inline;", "display: block;", "display: grid;"], 0),
                q("What happens when an element is styled with display: none;?", ["It is completely removed from the page layout and takes zero space", "It turns transparent but keeps its empty space", "It becomes grayed out", "It shrinks to 1 pixel"], 0),
                q("What is the difference between display: none; and visibility: hidden;?", ["visibility: hidden hides the element while keeping its empty space on the page", "They are identical in every way", "display: none keeps the space", "visibility: hidden removes the element from DOM"], 0),
                q("Which property controls transparency of an element from 0.0 to 1.0?", ["opacity", "transparency", "alpha", "ghost"], 0),
                q("Which property changes the shape of the mouse pointer when hovering over a button?", ["cursor: pointer;", "mouse: hand;", "pointer: click;", "hover-mouse: arrow;"], 0),
                q("Which property controls whether an element can receive mouse click events?", ["pointer-events: none;", "mouse-click: disabled;", "clickable: false;", "events: off;"], 0),
            ],
            "2": [ # CSS Medium Level 2 - Positioning & Layout Layers
                q("What is the default position value for all HTML elements?", ["static", "relative", "absolute", "fixed"], 0),
                q("Which position value positions an element relative to its normal position in document flow?", ["relative", "static", "fixed", "absolute"], 0),
                q("Which position value positions an element relative to its closest positioned ancestor?", ["absolute", "fixed", "static", "relative"], 0),
                q("Which position value pins an element to the browser viewport so it stays when scrolling?", ["fixed", "absolute", "relative", "static"], 0),
                q("Which property controls the vertical stacking order (which element is on top of which)?", ["z-index", "layer-index", "depth", "stack-order"], 0),
                q("For z-index to take effect, what must the element's position property NOT be?", ["static", "relative", "absolute", "fixed"], 0),
                q("Which position value acts like relative until scroll reaches a point, then acts like fixed?", ["sticky", "pinned", "floating", "dynamic"], 0),
                q("Which four directional offset properties are used with positioned elements?", ["top, right, bottom, left", "up, down, left, right", "north, south, east, west", "x, y, z, w"], 0),
            ],
            "3": [ # CSS Medium Level 3 - Interactive Pseudo-Classes
                q("Which pseudo-class styles an element when the user moves the mouse over it?", [":hover", ":active", ":focus", ":visited"], 0),
                q("Which pseudo-class styles a button at the exact moment it is being clicked down?", [":active", ":hover", ":focus", ":target"], 0),
                q("Which pseudo-class styles an input when the user clicks inside to type?", [":focus", ":active", ":hover", ":typing"], 0),
                q("Which pseudo-class targets a link that the user has already clicked in the past?", [":visited", ":history", ":clicked", ":past"], 0),
                q("Which pseudo-class targets the very first child element among its siblings?", [":first-child", ":initial", ":start", ":first-item"], 0),
                q("Which pseudo-class targets the last child element among its siblings?", [":last-child", ":end", ":final", ":last-of"], 0),
                q("Which pseudo-class selects every even or odd element in a list (like striped tables)?", [":nth-child(even)", ":even-items", ":alternate", ":stripe"], 0),
                q("Which pseudo-class styles a disabled form button?", [":disabled", ":inactive", ":locked", ":off"], 0),
            ],
            "4": [ # CSS Medium Level 4 - Flexbox Fundamentals
                q("Which CSS property turns a container into a flexible flexbox container?", ["display: flex;", "flexbox: true;", "display: box;", "layout: flex;"], 0),
                q("Which property aligns flex items along the main horizontal axis (e.g. center, space-between)?", ["justify-content", "align-items", "align-content", "flex-align"], 0),
                q("Which property aligns flex items along the cross vertical axis (e.g. center, stretch)?", ["align-items", "justify-content", "flex-cross", "valign"], 0),
                q("Which property changes the main axis direction to vertical columns?", ["flex-direction: column;", "flex-axis: vertical;", "direction: down;", "layout-flow: column;"], 0),
                q("Which property allows flex items to wrap onto multiple lines if they run out of space?", ["flex-wrap: wrap;", "wrap-items: true;", "flex-multiline: on;", "overflow-wrap: flex;"], 0),
                q("Which modern property sets the empty spacing between flex items without using margins?", ["gap", "space-between", "item-spacing", "flex-gap-size"], 0),
                q("How do you perfectly center an element both horizontally and vertically with Flexbox?", ["display: flex; justify-content: center; align-items: center;", "display: block; center: both;", "margin: auto auto;", "align: middle center;"], 0),
                q("Which property controls how much a flex item grows relative to sibling items?", ["flex-grow", "flex-expand", "flex-size", "flex-weight"], 0),
            ],
            "5": [ # CSS Medium Level 5 - Shadows, Outlines & Box-Sizing
                q("Which box-sizing value includes padding and borders inside the specified width?", ["box-sizing: border-box;", "box-sizing: content-box;", "box-sizing: padding-box;", "box-sizing: total;"], 0),
                q("What is the default browser box-sizing value that causes padding to add extra width?", ["content-box", "border-box", "margin-box", "native-box"], 0),
                q("Which property adds a soft drop shadow beneath an element box?", ["box-shadow", "shadow", "drop-shadow", "element-shadow"], 0),
                q("Which property adds a shadow effect around text letters?", ["text-shadow", "font-shadow", "letter-shadow", "glow"], 0),
                q("Which property creates a line outside the border that does NOT take up layout space?", ["outline", "outer-border", "stroke", "ring"], 0),
                q("Which property smoothly changes CSS values over a duration when hovering?", ["transition", "animation-delay", "transform-time", "smooth-change"], 0),
                q("How do you specify a 0.3 second transition on all changed properties?", ["transition: all 0.3s ease;", "animate: 0.3s all;", "speed: 0.3s;", "ease: 300ms;"], 0),
                q("Which property rotates, scales, or slants an element on screen?", ["transform", "morph", "change", "convert"], 0),
            ]
        },
        "Hard": {
            "1": [ # CSS Hard Level 1 - Responsive Design & Units
                q("What rule is used in CSS to apply styles only at specific screen widths (mobile vs desktop)?", ["@media", "@screen", "@viewport", "@device"], 0),
                q("Which media query condition applies styles on screens 768px wide or smaller?", ["@media (max-width: 768px)", "@media (min-width: 768px)", "@media [width <= 768px]", "@media screen and 768px"], 0),
                q("Which relative font unit is calculated relative to the root <html> font size?", ["rem", "em", "vh", "vw"], 0),
                q("Which relative font unit is calculated relative to the immediate parent element's font size?", ["em", "rem", "px", "%"], 0),
                q("What does 100vh represent in CSS sizing?", ["100% of the viewport viewport height", "100 visual horizontal pixels", "100 vertical header lines", "100 visible hex units"], 0),
                q("What does 50vw represent in CSS sizing?", ["50% of the viewport viewport width", "50 variable words", "50 vector widths", "50 visual weights"], 0),
                q("What is the mobile-first CSS design approach?", ["Writing base styles for mobile screens first, then adding min-width media queries for desktop", "Designing only for smartphones and ignoring PC", "Using JavaScript to detect device brand", "Disabling CSS on mobile phones"], 0),
                q("Which function allows combining different CSS units like calc(100% - 40px)?", ["calc()", "compute()", "math()", "eval()"], 0),
            ],
            "2": [ # CSS Hard Level 2 - CSS Grid Layout
                q("Which property activates a two-dimensional grid container in CSS?", ["display: grid;", "display: table-grid;", "grid-layout: on;", "display: matrix;"], 0),
                q("Which property defines the number and width of columns in a CSS grid?", ["grid-template-columns", "grid-columns-count", "columns-width", "grid-cols"], 0),
                q("Which flexible unit represents a fraction of the free space in a CSS grid?", ["fr", "flex", "ratio", "pt"], 0),
                q("How do you define 3 equal columns in CSS grid using the repeat function?", ["grid-template-columns: repeat(3, 1fr);", "grid-cols: 3 equal;", "columns: repeat(3);", "grid-template: 3fr 3fr 3fr;"], 0),
                q("Which property sets the gutter gap spacing between rows and columns in a grid?", ["gap", "grid-margin", "cell-spacing", "gutter"], 0),
                q("What is the primary difference between Flexbox and CSS Grid?", ["Grid is 2-dimensional (rows & columns); Flexbox is 1-dimensional (row or column)", "Flexbox is for images; Grid is for text", "Grid only works in Chrome", "Flexbox was deprecated in CSS3"], 0),
                q("Which property places a grid item across columns from line 1 to line 3?", ["grid-column: 1 / 3;", "col-span: 1 to 3;", "grid-span: 2 cols;", "column-range: 1-3;"], 0),
                q("Which grid property automatically fits as many columns as will fit without media queries?", ["grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));", "grid-auto-columns: dynamic;", "grid-responsive: true;", "columns: auto-wrap;"], 0),
            ],
            "3": [ # CSS Hard Level 3 - CSS Variables & Specificity
                q("How do you declare a custom property (CSS variable) in CSS?", ["--main-color: #3498db;", "$main-color = #3498db;", "@var main-color: #3498db;", "let main-color = #3498db;"], 0),
                q("How do you use a custom property (CSS variable) in a style rule?", ["var(--main-color)", "get(--main-color)", "use($main-color)", "val(--main-color)"], 0),
                q("Where are global CSS variables typically declared so they inherit everywhere?", [":root", "body", "html", "*"], 0),
                q("Which selector type has the highest natural specificity hierarchy in CSS?", ["ID selector (#id)", "Class selector (.class)", "Element selector (div)", "Universal selector (*)"], 0),
                q("What keyword overrides normal CSS cascade specificity (should be used sparingly)?", ["!important", "!override", "!force", "!priority"], 0),
                q("Which pseudo-element inserts virtual content before the content of an element?", ["::before", "::prepend", "::start", "::front"], 0),
                q("Which CSS property is required for ::before or ::after to display anything?", ["content", "display", "text", "value"], 0),
                q("Which pseudo-element allows styling the first letter of a paragraph differently?", ["::first-letter", "::initial", "::cap", "::start-char"], 0),
            ],
            "4": [ # CSS Hard Level 4 - Animations & Keyframes
                q("Which at-rule defines keyframes for a complex CSS animation sequence?", ["@keyframes", "@animation", "@frames", "@motion"], 0),
                q("Which property binds an animation name and duration to an element?", ["animation: spin 2s infinite linear;", "animate: spin 2s;", "motion-bind: spin;", "keyframes: spin 2s;"], 0),
                q("Which property controls whether an animation plays forward, backward, or alternates?", ["animation-direction", "animation-flow", "animation-reverse", "animation-cycle"], 0),
                q("Which value keeps the final state styles of an animation after it finishes?", ["animation-fill-mode: forwards;", "animation-keep: true;", "animation-end: hold;", "animation-state: stay;"], 0),
                q("Which transform function scales an element to 1.2 times its original size on hover?", ["transform: scale(1.2);", "zoom: 120%;", "size: 1.2x;", "scale-factor: 1.2;"], 0),
                q("Which transform function shifts an element 20px horizontally and 10px vertically?", ["transform: translate(20px, 10px);", "position-shift: 20px 10px;", "move: 20px 10px;", "offset: 20px, 10px;"], 0),
                q("Which transform function rotates an element by 45 degrees clockwise?", ["transform: rotate(45deg);", "turn: 45deg;", "spin: 45deg;", "angle: 45;"], 0),
                q("Which property changes the origin point around which transforms rotate or scale?", ["transform-origin", "origin-point", "transform-pivot", "center-point"], 0),
            ],
            "5": [ # CSS Hard Level 5 - Advanced Visual Effects & Filters
                q("Which CSS property applies visual blur or grayscale filters directly to an element?", ["filter", "effects", "visual-mod", "image-filter"], 0),
                q("Which filter function blurs an image by 5 pixels in CSS?", ["filter: blur(5px);", "filter: soften(5px);", "effects: blur(5px);", "blur: 5px;"], 0),
                q("Which modern property creates a frosted-glass translucent effect on background content?", ["backdrop-filter: blur(10px);", "glass-effect: true;", "frosted-blur: 10px;", "background-blur: 10px;"], 0),
                q("Which property clips an element into geometric shapes like circles, polygons, or stars?", ["clip-path", "mask-shape", "cut-out", "crop-polygon"], 0),
                q("Which function creates a smooth diagonal color gradient in CSS?", ["background: linear-gradient(45deg, red, blue);", "background: color-blend(red, blue);", "gradient: diagonal(red, blue);", "color: gradient(red, blue);"], 0),
                q("Which property prevents text from wrapping to the next line?", ["white-space: nowrap;", "text-wrap: none;", "word-break: stop;", "overflow-wrap: none;"], 0),
                q("Which combination cuts off overflowing text and shows an ellipsis ('...')?", ["overflow: hidden; white-space: nowrap; text-overflow: ellipsis;", "text-cut: true; show-dots: true;", "ellipsis: on;", "clip: text; dots: true;"], 0),
                q("Which property controls whether an image preserves its aspect ratio within a fixed box?", ["object-fit: cover;", "image-scale: preserve;", "aspect-ratio: locked;", "fit-mode: cover;"], 0),
            ]
        }
    },
    "JavaScript": {
        "Easy": {
            "1": [ # JS Easy Level 1 - Introduction & Output
                q("Which tag is used to write or import JavaScript code in an HTML file?", ["<script>", "<js>", "<javascript>", "<code>"], 0),
                q("Which function prints messages directly to the browser developer console?", ["console.log('Hello');", "print('Hello');", "System.out.println('Hello');", "echo 'Hello';"], 0),
                q("Which built-in function displays a popup modal alert dialog in the browser?", ["alert('Notice');", "popup('Notice');", "dialog('Notice');", "notify('Notice');"], 0),
                q("How do you write a single-line comment in JavaScript?", ["// comment", "/* comment */", "<!-- comment -->", "# comment"], 0),
                q("How do you write a multi-line comment block in JavaScript?", ["/* comment */", "// comment", "<!-- comment -->", "#* comment *#"], 0),
                q("Which file extension is used for external JavaScript files?", [".js", ".java", ".script", ".ts"], 0),
                q("Which keyword declares a variable whose value can be reassigned later?", ["let", "const", "fixed", "static"], 0),
                q("Which keyword declares a variable whose value cannot be reassigned (constant)?", ["const", "let", "var", "freeze"], 0),
            ],
            "2": [ # JS Easy Level 2 - Data Types & Basic Variables
                q("Which of the following is a String data type in JavaScript?", ["'Hello World'", "123", "true", "null"], 0),
                q("Which of the following represents a Boolean value in JavaScript?", ["true or false", "'yes' or 'no'", "1 or 0", "valid or invalid"], 0),
                q("What operator is used to check the data type of a variable in JavaScript?", ["typeof", "type()", "instance", "datatype"], 0),
                q("What is the data type of the value 42 in JavaScript?", ["number", "integer", "string", "float"], 0),
                q("What special value represents an intentional absence of any object value?", ["null", "undefined", "NaN", "void"], 0),
                q("What is the value of a variable that has been declared but never assigned a value?", ["undefined", "null", "0", "empty"], 0),
                q("What does NaN stand for in JavaScript?", ["Not a Number", "New assigned Number", "Null and Negative", "No authorized Notation"], 0),
                q("What symbol is used for variable assignment in JavaScript?", ["= (single equals)", "== (double equals)", "=== (triple equals)", ":="], 0),
            ],
            "3": [ # JS Easy Level 3 - Basic Operators & Arithmetic
                q("What is the result of the expression 5 + 3 in JavaScript?", ["8", "53", "15", "2"], 0),
                q("Which operator calculates the remainder of a division (modulo)?", ["%", "/", "#", "mod"], 0),
                q("What is the result of the expression 10 % 3 in JavaScript?", ["1", "3", "0", "3.33"], 0),
                q("What is the result of 'Java' + 'Script' in JavaScript?", ["'JavaScript'", "'Java Script'", "NaN", "Error"], 0),
                q("What is the result of '5' + 5 in JavaScript (type coercion)?", ["'55' (string)", "10 (number)", "NaN", "Error"], 0),
                q("Which operator increases a numeric variable's value by 1?", ["++", "+=2", "--", "**"], 0),
                q("Which operator decreases a numeric variable's value by 1?", ["--", "++", "//", "-="], 0),
                q("Which operator raises a number to a power (exponentiation, like 2 ** 3)?", ["**", "^", "pow", "%%"], 0),
            ],
            "4": [ # JS Easy Level 4 - Conditionals & Comparisons
                q("Which comparison operator checks value equality with type conversion?", ["==", "===", "=", "!="], 0),
                q("Which comparison operator checks strict equality (both value AND type must match)?", ["===", "==", "=", "equals"], 0),
                q("What does 5 === '5' evaluate to in JavaScript?", ["false (different types: number vs string)", "true", "undefined", "NaN"], 0),
                q("What does 5 == '5' evaluate to in JavaScript?", ["true (coerced)", "false", "undefined", "error"], 0),
                q("Which statement executes code only if a specified condition evaluates to true?", ["if (condition) { }", "while (condition) { }", "for (condition) { }", "switch (condition) { }"], 0),
                q("Which clause runs when the preceding if condition is false?", ["else", "otherwise", "then", "catch"], 0),
                q("Which comparison operator checks if a value is strictly NOT equal to another?", ["!==", "!=", "<>", "not =="], 0),
                q("Which comparison operator checks if a value is greater than another?", [">", "<", ">=", "<="], 0),
            ],
            "5": [ # JS Easy Level 5 - Basic Loops
                q("Which loop is typically used when you know how many times to repeat code?", ["for loop", "while loop", "do loop", "switch loop"], 0),
                q("In 'for (let i = 0; i < 5; i++)', how many times will the loop run?", ["5 times (0, 1, 2, 3, 4)", "4 times", "6 times", "Infinite"], 0),
                q("Which loop continues running as long as its condition remains true?", ["while loop", "if loop", "for loop", "switch loop"], 0),
                q("Which keyword immediately terminates and exits a loop early?", ["break", "continue", "stop", "exit"], 0),
                q("Which keyword skips the current iteration and jumps to the next cycle of the loop?", ["continue", "break", "skip", "pass"], 0),
                q("What happens if a while loop condition never becomes false?", ["It creates an infinite loop that can freeze the browser tab", "The browser ignores it", "It runs once and stops", "It turns into an if statement"], 0),
                q("Which loop always executes its code block at least once before checking the condition?", ["do...while loop", "while loop", "for loop", "for...in loop"], 0),
                q("In a standard zero-indexed counting loop from 0 to 9, what is the starting value of i?", ["0", "1", "-1", "null"], 0),
            ]
        },
        "Medium": {
            "1": [ # JS Medium Level 1 - Logical Operators & Truthy/Falsy
                q("Which logical operator represents AND in JavaScript?", ["&&", "||", "AND", "&"], 0),
                q("Which logical operator represents OR in JavaScript?", ["||", "&&", "OR", "|"], 0),
                q("Which logical operator flips true to false and false to true (NOT)?", ["!", "NOT", "~", "--"], 0),
                q("What does (true && false) evaluate to?", ["false", "true", "undefined", "null"], 0),
                q("What does (true || false) evaluate to?", ["true", "false", "undefined", "null"], 0),
                q("Which of the following values is considered 'falsy' in JavaScript?", ["0", "'0'", "[] (empty array)", "{} (empty object)"], 0),
                q("Which of the following values is considered 'truthy' in JavaScript?", ["'hello' (non-empty string)", "'' (empty string)", "0", "null"], 0),
                q("What is the shorthand ternary operator syntax for simple conditional assignment?", ["condition ? valueIfTrue : valueIfFalse", "condition -> ifTrue : ifFalse", "if condition then true else false", "check(condition, true, false)"], 0),
            ],
            "2": [ # JS Medium Level 2 - Functions Basics
                q("Which keyword is used to declare a standard named function in JavaScript?", ["function", "def", "method", "fun"], 0),
                q("How do you invoke (call) a function named greet in JavaScript?", ["greet();", "call greet;", "invoke greet();", "run(greet);"], 0),
                q("Which keyword outputs a value from a function back to the caller?", ["return", "output", "send", "give"], 0),
                q("What are the variables listed in a function's declaration parentheses called?", ["Parameters", "Arguments", "Constants", "Return values"], 0),
                q("What are the actual values passed into a function when calling it called?", ["Arguments", "Parameters", "Variables", "Signatures"], 0),
                q("What does a function return by default if it has no return statement?", ["undefined", "null", "0", "false"], 0),
                q("What is the scope of a variable declared with let inside a function?", ["Local to that function only", "Global across the entire app", "Accessible in all HTML files", "Window scope"], 0),
                q("Can a function in JavaScript call itself recursively?", ["Yes, recursion is fully supported", "No, it causes an immediate syntax error", "Only in Node.js", "Only with external plugins"], 0),
            ],
            "3": [ # JS Medium Level 3 - Arrays Fundamentals
                q("How do you declare an array containing numbers 1, 2, and 3 in JavaScript?", ["let arr = [1, 2, 3];", "let arr = (1, 2, 3);", "let arr = {1, 2, 3};", "let arr = <1, 2, 3>;"], 0),
                q("What is the index of the first element in a JavaScript array?", ["0", "1", "-1", "null"], 0),
                q("How do you get the number of items in an array named items?", ["items.length", "items.size()", "items.count", "items.len"], 0),
                q("How do you access the second element in an array named fruits?", ["fruits[1]", "fruits[2]", "fruits(1)", "fruits.second"], 0),
                q("How do you access the last item of an array named arr?", ["arr[arr.length - 1]", "arr[arr.length]", "arr[-1]", "arr.last()"], 0),
                q("Can a single JavaScript array hold elements of different data types?", ["Yes, arrays can mix numbers, strings, booleans, and objects", "No, all items must be the same type", "Only if declared with var", "Only up to 5 items"], 0),
                q("What is the index of the last element in an array with 10 items?", ["9", "10", "11", "8"], 0),
                q("What does arr[100] return if the array only has 3 elements?", ["undefined", "null", "0", "Error"], 0),
            ],
            "4": [ # JS Medium Level 4 - Common Array Methods
                q("Which array method adds a new element to the END of an array?", ["push()", "pop()", "shift()", "unshift()"], 0),
                q("Which array method removes and returns the LAST element of an array?", ["pop()", "push()", "shift()", "slice()"], 0),
                q("Which array method removes and returns the FIRST element of an array?", ["shift()", "unshift()", "pop()", "splice()"], 0),
                q("Which array method adds a new element to the BEGINNING of an array?", ["unshift()", "shift()", "push()", "insert()"], 0),
                q("Which array method returns the index of the first occurrence of an item, or -1 if not found?", ["indexOf()", "findIndex()", "search()", "locate()"], 0),
                q("Which array method checks if an array contains a specific value and returns true/false?", ["includes()", "has()", "contains()", "exists()"], 0),
                q("Which array method joins all array elements into a single string separated by commas?", ["join()", "concat()", "toString()", "merge()"], 0),
                q("Which array method reverses the order of elements in place?", ["reverse()", "invert()", "flip()", "backward()"], 0),
            ],
            "5": [ # JS Medium Level 5 - DOM Selection Basics
                q("What does DOM stand for in web development?", ["Document Object Model", "Data Object Management", "Dynamic Output Module", "Digital Ordinance Map"], 0),
                q("Which method selects a single HTML element by its ID attribute?", ["document.getElementById('title')", "document.getElement('title')", "document.selectId('title')", "document.findId('title')"], 0),
                q("Which modern method selects the first element matching any CSS selector?", ["document.querySelector('.btn')", "document.select('.btn')", "document.find('.btn')", "document.getCSS('.btn')"], 0),
                q("Which method selects ALL elements matching a CSS selector as a NodeList?", ["document.querySelectorAll('.item')", "document.selectAll('.item')", "document.getAll('.item')", "document.elements('.item')"], 0),
                q("Which property changes the plain text content inside an HTML element?", ["element.textContent = 'Hello';", "element.text = 'Hello';", "element.write = 'Hello';", "element.val = 'Hello';"], 0),
                q("Which property sets or gets the raw HTML markup inside an element?", ["element.innerHTML", "element.contentHTML", "element.markup", "element.rawHTML"], 0),
                q("How do you change the background color of an element via JavaScript?", ["element.style.backgroundColor = 'blue';", "element.css.background = 'blue';", "element.color.bg = 'blue';", "element.style('bg', 'blue');"], 0),
                q("Which property gets or sets the value typed inside a text <input> element?", ["input.value", "input.text", "input.content", "input.val()"], 0),
            ]
        },
        "Hard": {
            "1": [ # JS Hard Level 1 - Event Handling & Interactivity
                q("Which method attaches an event handler function to an element without overwriting existing ones?", ["element.addEventListener('click', fn)", "element.attach('click', fn)", "element.on('click', fn)", "element.bind('click', fn)"], 0),
                q("Which event fires when a user clicks on an element?", ["click", "press", "tap", "hit"], 0),
                q("Which event fires when the user types or changes value inside an input field?", ["input", "type", "change-text", "press"], 0),
                q("Which event fires when an HTML form is submitted?", ["submit", "send", "post", "finish"], 0),
                q("Which method prevents a form submission from refreshing the entire page?", ["event.preventDefault()", "event.stopPropagation()", "event.cancel()", "event.stop()"], 0),
                q("Which property on the event object refers to the element that triggered the event?", ["event.target", "event.element", "event.sender", "event.source"], 0),
                q("Which method adds a CSS class name to an element's classList?", ["element.classList.add('active')", "element.classes.push('active')", "element.addClass('active')", "element.className.add('active')"], 0),
                q("Which method toggles a CSS class on an element (adds if missing, removes if present)?", ["element.classList.toggle('active')", "element.classList.switch('active')", "element.toggle('active')", "element.classList.flip('active')"], 0),
            ],
            "2": [ # JS Hard Level 2 - Objects & Key-Value Pairs
                q("How do you declare a simple object with properties name and age in JavaScript?", ["let person = { name: 'Alex', age: 17 };", "let person = [ name: 'Alex', age: 17 ];", "let person = ( name = 'Alex', age = 17 );", "let person = < name: 'Alex', age: 17 >;"], 0),
                q("How do you access the name property of an object named student using dot notation?", ["student.name", "student->name", "student::name", "student[name]"], 0),
                q("How do you access an object property using bracket notation with a variable key?", ["obj[key]", "obj.key", "obj(key)", "obj->key"], 0),
                q("What is a function stored as a property inside an object called?", ["A method", "A parameter", "A prototype", "An attribute"], 0),
                q("Which keyword refers to the current object executing a method?", ["this", "self", "me", "current"], 0),
                q("Which Object method returns an array of all keys in an object?", ["Object.keys(obj)", "obj.getKeys()", "Object.properties(obj)", "Object.names(obj)"], 0),
                q("Which Object method returns an array of all property values in an object?", ["Object.values(obj)", "obj.getValues()", "Object.data(obj)", "Object.items(obj)"], 0),
                q("Which operator checks if a property key exists in an object?", ["'age' in person", "person.has('age')", "person.contains('age')", "exists('age', person)"], 0),
            ],
            "3": [ # JS Hard Level 3 - Modern ES6 Features
                q("What is the concise arrow function syntax for adding two numbers a and b?", ["(a, b) => a + b", "function(a, b) -> a + b", "(a, b) ==> a + b", "def(a, b) => a + b"], 0),
                q("What backtick syntax allows embedding variables directly inside strings (${name})?", ["Template literals (Template strings)", "String interpolation marks", "Macro strings", "Dynamic literals"], 0),
                q("How do you write a template literal combining text with a variable score?", ["`Your score is ${score}`", "'Your score is ${score}'", "\"Your score is #{score}\"", "('Your score is ' + ${score})"], 0),
                q("What syntax allows unpacking values from arrays or objects into distinct variables?", ["Destructuring assignment", "Unpacking notation", "Splitting syntax", "Extraction binding"], 0),
                q("What does the spread operator (...) do when used with an array like [...arr1, ...arr2]?", ["Expands elements into individual items to combine or copy arrays", "Multiplies elements", "Calculates the average", "Deletes duplicates"], 0),
                q("How do you provide a default parameter value in a function definition?", ["function greet(name = 'Guest') { }", "function greet(name : 'Guest') { }", "function greet(default name = 'Guest') { }", "function greet(name or 'Guest') { }"], 0),
                q("Which keyword is used to export functions or variables from a JavaScript module?", ["export", "public", "share", "module.out"], 0),
                q("Which keyword is used to import functions or variables from another module file?", ["import", "require", "include", "fetch"], 0),
            ],
            "4": [ # JS Hard Level 4 - Higher-Order Array Iterators
                q("Which array method executes a provided callback function once for each array element?", ["forEach()", "loop()", "each()", "iterate()"], 0),
                q("Which array method creates a NEW array populated with the results of calling a function on every item?", ["map()", "forEach()", "transform()", "collect()"], 0),
                q("Which array method creates a NEW array containing only elements that pass a test condition?", ["filter()", "select()", "find()", "test()"], 0),
                q("Which array method returns the FIRST element that satisfies a test condition?", ["find()", "search()", "locate()", "filterFirst()"], 0),
                q("Which array method checks if AT LEAST ONE element passes a test and returns boolean?", ["some()", "any()", "exists()", "check()"], 0),
                q("Which array method checks if EVERY single element passes a test and returns boolean?", ["every()", "all()", "each()", "validateAll()"], 0),
                q("Which array method reduces an array down to a single accumulated value (like a total sum)?", ["reduce()", "aggregate()", "sum()", "fold()"], 0),
                q("What does [1, 2, 3].map(x => x * 2) return?", ["[2, 4, 6]", "[1, 2, 3]", "12", "undefined"], 0),
            ],
            "5": [ # JS Hard Level 5 - Asynchronous JS & Web APIs
                q("Which built-in function executes code after a specified delay in milliseconds?", ["setTimeout(fn, 1000)", "delay(fn, 1000)", "sleep(1000, fn)", "wait(fn, 1000)"], 0),
                q("Which built-in function repeatedly calls a function at fixed time intervals?", ["setInterval(fn, 1000)", "repeat(fn, 1000)", "loop(fn, 1000)", "timer(fn, 1000)"], 0),
                q("Which method cancels a recurring timer created with setInterval?", ["clearInterval(timerId)", "stopInterval(timerId)", "cancelTimer(timerId)", "endInterval(timerId)"], 0),
                q("What object represents the eventual completion or failure of an asynchronous operation?", ["A Promise", "A Callback", "An EventLoop", "A FutureTask"], 0),
                q("Which keywords provide clean synchronous-like syntax for working with Promises?", ["async and await", "defer and wait", "try and future", "sync and yield"], 0),
                q("Which modern browser API makes asynchronous HTTP network requests to fetch data?", ["fetch()", "http.get()", "request()", "ajax()"], 0),
                q("Which method parses a JSON formatted string into a JavaScript object?", ["JSON.parse(str)", "JSON.stringify(str)", "JSON.toObject(str)", "JSON.decode(str)"], 0),
                q("Which Web Storage API stores key-value pairs persistently across browser restarts?", ["localStorage", "sessionStorage", "cookies", "cacheStorage"], 0),
            ]
        }
    },
    "Java": {
        "Easy": {
            "1": [ # Java Easy Level 1 - Introduction & Main Structure
                q("Which method is the required starting entry point of every standalone Java program?", ["public static void main(String[] args)", "public void start()", "static main()", "public static run()"], 0),
                q("Which keyword is used to declare a class in Java?", ["class", "Class", "struct", "object"], 0),
                q("What file extension must Java source code files have?", [".java", ".class", ".jav", ".jar"], 0),
                q("Which statement prints text to the screen and moves to a new line?", ["System.out.println('Text');", "System.print('Text');", "print('Text');", "Console.write('Text');"], 0),
                q("Which statement prints text to the screen WITHOUT moving to a new line?", ["System.out.print('Text');", "System.out.println('Text');", "System.printLine('Text');", "out.print('Text');"], 0),
                q("Every Java statement must end with which punctuation mark?", ["; (semicolon)", ": (colon)", ". (period)", ", (comma)"], 0),
                q("How do you write a single-line comment in Java?", ["// comment", "# comment", "/* comment", "<!-- comment -->"], 0),
                q("What happens when Java source code (.java) is compiled?", ["It is compiled into Java Bytecode (.class files)", "It compiles directly to x86 assembly", "It creates an HTML file", "It converts to JavaScript"], 0),
            ],
            "2": [ # Java Easy Level 2 - Primitive Data Types
                q("Which primitive type is used to store standard whole integers in Java?", ["int", "double", "boolean", "char"], 0),
                q("Which primitive type is commonly used to store decimal numbers (floating point)?", ["double", "int", "boolean", "decimal"], 0),
                q("Which primitive type stores a true or false value in Java?", ["boolean", "bool", "truth", "bit"], 0),
                q("Which primitive type stores a single Unicode character enclosed in single quotes?", ["char", "String", "character", "letter"], 0),
                q("Which class is used in Java to store text sequences of multiple characters?", ["String", "string", "Text", "Chars"], 0),
                q("How do you declare an integer variable named age with value 16?", ["int age = 16;", "integer age = 16;", "var age : 16;", "age = 16 int;"], 0),
                q("What is the default value of an uninitialized int instance field in Java?", ["0", "null", "1", "-1"], 0),
                q("What is the default value of an uninitialized boolean instance field in Java?", ["false", "true", "null", "0"], 0),
            ],
            "3": [ # Java Easy Level 3 - Basic Operators & Arithmetic
                q("What is the result of 15 / 4 when both numbers are integers in Java?", ["3 (integer division truncates decimal)", "3.75", "4", "3.5"], 0),
                q("Which operator finds the remainder of integer division in Java?", ["%", "/", "mod", "\\"], 0),
                q("What is the result of 17 % 5 in Java?", ["2", "3", "1", "5"], 0),
                q("What does the ++ operator do to a variable?", ["Increments its value by 1", "Doubles its value", "Decrements by 1", "Squares it"], 0),
                q("What does the -- operator do to a variable?", ["Decrements its value by 1", "Increments by 1", "Divides by 2", "Inverts sign"], 0),
                q("What is the result of string concatenation: \"Level \" + 5?", ["\"Level 5\"", "\"Level + 5\"", "Error", "\"Level5.0\""], 0),
                q("What does the assignment operator += do in x += 5?", ["Adds 5 to x (x = x + 5)", "Sets x equal to 5", "Compares x with 5", "Multiplies x by 5"], 0),
                q("Which operator performs multiplication in Java?", ["*", "x", "X", "**"], 0),
            ],
            "4": [ # Java Easy Level 4 - Basic If-Else Decisions
                q("Which comparison operator checks if two primitive values are equal in Java?", ["==", "=", "===", "equals"], 0),
                q("Which comparison operator checks if two primitive values are NOT equal?", ["!=", "<>", "!==", "not =="], 0),
                q("Which keyword starts a conditional branch decision in Java?", ["if", "when", "check", "test"], 0),
                q("Which keyword provides an alternative code block if the if condition is false?", ["else", "otherwise", "then", "catch"], 0),
                q("Which keyword tests another condition if the first if condition was false?", ["else if", "elif", "otherwise if", "then if"], 0),
                q("Which comparison operator checks if a value is strictly less than another?", ["<", ">", "<=", ">="], 0),
                q("Which comparison operator checks if a value is greater than or equal to another?", [">=", "<=", ">", "=>"], 0),
                q("Can an if statement in Java exist on its own without an else block?", ["Yes, else is completely optional", "No, else is mandatory", "Only inside methods", "Only in Java 17+"], 0),
            ],
            "5": [ # Java Easy Level 5 - Basic Loops (For & While)
                q("Which loop is typically used when you know the exact number of iterations beforehand?", ["for loop", "while loop", "do loop", "switch loop"], 0),
                q("In 'for (int i = 0; i < 5; i++)', how many times does the loop body execute?", ["5 times (i = 0, 1, 2, 3, 4)", "4 times", "6 times", "0 times"], 0),
                q("Which loop repeats while a boolean condition remains true?", ["while loop", "if loop", "static loop", "case loop"], 0),
                q("Which keyword immediately exits and breaks out of a loop?", ["break", "continue", "stop", "return"], 0),
                q("Which keyword skips the rest of the current iteration and starts the next loop cycle?", ["continue", "skip", "break", "next"], 0),
                q("Which loop guarantees that the code inside executes AT LEAST once before checking condition?", ["do-while loop", "while loop", "for loop", "enhanced for loop"], 0),
                q("What happens if a loop's condition never becomes false?", ["An infinite loop occurs and keeps running", "The program compiles with error", "Java stops it after 100 turns", "It switches to an if"], 0),
                q("In 'for (int i = 1; i <= 3; i++)', what values does i take?", ["1, 2, 3", "0, 1, 2", "1, 2", "1, 2, 3, 4"], 0),
            ]
        },
        "Medium": {
            "1": [ # Java Medium Level 1 - Logical Operators & Boolean Expressions
                q("Which operator represents logical AND in Java?", ["&&", "&", "AND", "and"], 0),
                q("Which operator represents logical OR in Java?", ["||", "|", "OR", "or"], 0),
                q("Which operator represents logical NOT (inversion) in Java?", ["!", "NOT", "~", "^"], 0),
                q("What does (true && false) evaluate to in Java?", ["false", "true", "1", "0"], 0),
                q("What does (true || false) evaluate to in Java?", ["true", "false", "1", "0"], 0),
                q("What does !true evaluate to in Java?", ["false", "true", "null", "error"], 0),
                q("What is short-circuit evaluation in (false && someMethod())?", ["Java skips executing someMethod() because the first condition is already false", "It throws an error", "It runs both anyway", "It inverts the result"], 0),
                q("What is the shorthand ternary conditional operator syntax in Java?", ["condition ? valueIfTrue : valueIfFalse", "condition -> ifTrue : ifFalse", "if(condition, true, false)", "condition : true ? false"], 0),
            ],
            "2": [ # Java Medium Level 2 - Arrays in Java
                q("How do you declare and initialize an integer array with values 10, 20, 30 in Java?", ["int[] numbers = {10, 20, 30};", "int numbers = [10, 20, 30];", "Array numbers = (10, 20, 30);", "int numbers[] = new [10, 20, 30];"], 0),
                q("What is the index of the first element in any Java array?", ["0", "1", "-1", "null"], 0),
                q("How do you determine the total number of elements in an array named scores?", ["scores.length", "scores.length()", "scores.size()", "scores.count"], 0),
                q("How do you access the third element in an array named arr?", ["arr[2]", "arr[3]", "arr(2)", "arr.get(2)"], 0),
                q("What exception is thrown if you try to access an invalid index like arr[10] on a 5-element array?", ["ArrayIndexOutOfBoundsException", "NullPointerException", "IndexInvalidException", "ArrayLimitException"], 0),
                q("Can the fixed length of a standard Java array be resized after creation?", ["No, standard arrays have a fixed size once created", "Yes, using arr.resize()", "Yes, using arr.add()", "Only if declared public"], 0),
                q("What is the default value of elements in a newly created int array (new int[5])?", ["0", "null", "-1", "undefined"], 0),
                q("What is the syntax for the enhanced for-each loop in Java to iterate through an array?", ["for (int num : numbers) { }", "for (each num in numbers) { }", "foreach (int num in numbers) { }", "for (int num -> numbers) { }"], 0),
            ],
            "3": [ # Java Medium Level 3 - Methods & Signatures
                q("What keyword is used when a method does not return any value?", ["void", "empty", "null", "none"], 0),
                q("How do you define a method that accepts two integers and returns their sum as an int?", ["public static int add(int a, int b) { return a + b; }", "public static void add(int a, int b) { return a + b; }", "def add(int a, int b) -> int", "public int:add(a, b)"], 0),
                q("What keyword is used inside a method to send a calculated value back to the caller?", ["return", "output", "send", "give"], 0),
                q("What is method overloading in Java?", ["Having multiple methods in the same class with the same name but different parameter lists", "Overriding a parent class method", "Writing a method that runs too slowly", "Calling a method repeatedly"], 0),
                q("What keyword allows a method or variable to belong to the class itself rather than instances?", ["static", "final", "public", "this"], 0),
                q("Can a static method directly call a non-static instance method without creating an object?", ["No, static context cannot directly access non-static instance methods", "Yes, freely", "Only in main", "Only if public"], 0),
                q("What are the variable declarations inside a method's header called?", ["Parameters", "Arguments", "Fields", "Properties"], 0),
                q("What are the actual values passed into a method call called?", ["Arguments", "Parameters", "Signatures", "Types"], 0),
            ],
            "4": [ # Java Medium Level 4 - User Input & Console Reading
                q("Which Java utility class is commonly used to read user input from the console?", ["Scanner (java.util.Scanner)", "Reader (java.io.Reader)", "InputParser", "ConsoleInput"], 0),
                q("Which package must be imported to use the Scanner class in Java?", ["import java.util.Scanner;", "import java.io.Scanner;", "import java.lang.Scanner;", "import java.system.Scanner;"], 0),
                q("How do you create a Scanner object attached to standard keyboard input?", ["Scanner sc = new Scanner(System.in);", "Scanner sc = new Scanner(System.out);", "Scanner sc = Scanner.open();", "Scanner sc = new Scanner();"], 0),
                q("Which Scanner method reads the next whole integer typed by the user?", ["sc.nextInt();", "sc.readInt();", "sc.getInt();", "sc.nextInteger();"], 0),
                q("Which Scanner method reads an entire line of text including spaces?", ["sc.nextLine();", "sc.nextText();", "sc.readLine();", "sc.next();"], 0),
                q("Which Scanner method reads a single word (stopping at whitespace)?", ["sc.next();", "sc.nextWord();", "sc.read();", "sc.readWord();"], 0),
                q("Which Scanner method reads a double decimal value?", ["sc.nextDouble();", "sc.readDouble();", "sc.getDouble();", "sc.nextFloat64();"], 0),
                q("Which method should you call on a Scanner when done reading to free system resources?", ["sc.close();", "sc.stop();", "sc.finish();", "sc.dispose();"], 0),
            ],
            "5": [ # Java Medium Level 5 - String Methods in Java
                q("How do you get the number of characters in a String named text in Java?", ["text.length()", "text.length", "text.size()", "text.count()"], 0),
                q("Which method correctly compares the textual content of two Strings for equality?", ["str1.equals(str2)", "str1 == str2", "str1.compare(str2)", "str1 === str2"], 0),
                q("Why should you NOT use == to compare the contents of two String objects in Java?", ["== compares memory object references, not character content", "== causes a compiler error on Strings", "== only compares the first character", "== is only for booleans"], 0),
                q("Which method returns the character at a specific index in a String?", ["str.charAt(index)", "str[index]", "str.get(index)", "str.char(index)"], 0),
                q("Which method converts all letters in a String to lowercase?", ["str.toLowerCase()", "str.toLower()", "str.lower()", "str.caseDown()"], 0),
                q("Which method converts all letters in a String to uppercase?", ["str.toUpperCase()", "str.toUpper()", "str.upper()", "str.capitalize()"], 0),
                q("Which method extracts a smaller portion of a String between start and end indices?", ["str.substring(start, end)", "str.slice(start, end)", "str.sub(start, end)", "str.part(start, end)"], 0),
                q("Which method checks if a String contains a specific sequence of characters?", ["str.contains(\"abc\")", "str.has(\"abc\")", "str.includes(\"abc\")", "str.exists(\"abc\")"], 0),
            ]
        },
        "Hard": {
            "1": [ # Java Hard Level 1 - Switch-Case & Flow Control
                q("Which statement tests a variable against multiple constant values using case branches?", ["switch statement", "if-then statement", "while-branch", "for-case"], 0),
                q("Which keyword prevents 'fall-through' execution into subsequent cases in a switch block?", ["break", "stop", "exit", "return"], 0),
                q("Which keyword provides a fallback branch in a switch if none of the cases match?", ["default", "else", "otherwise", "catch"], 0),
                q("Which types can be used in a Java switch statement?", ["byte, short, char, int, String, and enums", "Only boolean", "Only float and double", "Only arrays"], 0),
                q("What is the enhanced arrow switch syntax introduced in modern Java (Java 14+)?", ["case 1 -> System.out.println(\"One\");", "case 1: -> println(\"One\");", "case 1 => print(\"One\");", "when 1 -> print(\"One\");"], 0),
                q("What happens in a traditional switch if you omit the break statement on a matching case?", ["Execution falls through and runs the code of the next case too", "It throws a compilation error", "It exits the program", "It reverses the condition"], 0),
                q("Can multiple cases share the exact same code block in a traditional switch?", ["Yes, by stacking cases (e.g. case 1: case 2: ...)", "No, each case must have unique code", "Only in enums", "Only in Java 8"], 0),
                q("Can you use a boolean condition like (x > 10) directly as a case label in a Java switch?", ["No, case labels must be constant values, not boolean expressions", "Yes, freely", "Only with double", "Only in methods"], 0),
            ],
            "2": [ # Java Hard Level 2 - Object-Oriented Basics (Classes & Objects)
                q("Which keyword is used to instantiate (create) a new object from a class in Java?", ["new", "create", "make", "instantiate"], 0),
                q("What is a constructor in Java?", ["A special method with the same name as the class used to initialize new objects", "A tool that compiles code", "A destructor that deletes objects", "A private variable"], 0),
                q("What is the return type of a Java constructor?", ["Constructors do not specify any return type (not even void)", "void", "int", "Object"], 0),
                q("Which keyword refers to the current instance of the class inside an instance method?", ["this", "self", "super", "current"], 0),
                q("What access modifier restricts visibility so members are only accessible within their own class?", ["private", "public", "protected", "default"], 0),
                q("What access modifier allows members to be accessed from any class in any package?", ["public", "private", "protected", "internal"], 0),
                q("What is encapsulation in Object-Oriented Programming?", ["Hiding internal object state with private fields and providing public getter/setter methods", "Writing all code in one file", "Compiling code without errors", "Using static methods only"], 0),
                q("What is the purpose of a getter method in a Java class?", ["To return the value of a private instance variable", "To change the value of a variable", "To delete the object", "To print to console"], 0),
            ],
            "3": [ # Java Hard Level 3 - Inheritance & Polymorphism
                q("Which keyword is used by a child subclass to inherit from a parent superclass?", ["extends", "implements", "inherits", "super"], 0),
                q("Which keyword is used by a class to implement an interface in Java?", ["implements", "extends", "uses", "inherits"], 0),
                q("Which keyword refers to the superclass (parent) constructor or methods from a subclass?", ["super", "parent", "base", "this"], 0),
                q("Which annotation indicates that a method is intended to override a superclass method?", ["@Override", "@Super", "@Replace", "@Inherit"], 0),
                q("Does Java support multiple inheritance of classes (a class extending multiple classes)?", ["No, Java classes can only extend one superclass directly", "Yes, using extends A, B", "Only in Java 17", "Only for abstract classes"], 0),
                q("What is the ultimate root superclass of all classes in Java?", ["java.lang.Object", "java.lang.Class", "java.lang.System", "java.lang.Root"], 0),
                q("Which keyword prevents a class from being inherited or a method from being overridden?", ["final", "static", "sealed", "const"], 0),
                q("What is polymorphism in Java OOP?", ["The ability of different object types to respond to the same method call in their own way", "Converting code to binary", "Running code on multiple threads", "Creating arrays of different types"], 0),
            ],
            "4": [ # Java Hard Level 4 - Exception Handling
                q("Which block is used to enclose code that might throw an exception?", ["try block", "catch block", "finally block", "throw block"], 0),
                q("Which block catches and handles an exception thrown inside a try block?", ["catch block", "try block", "throw block", "error block"], 0),
                q("Which block ALWAYS executes whether an exception was thrown or not?", ["finally block", "always block", "final block", "catch block"], 0),
                q("Which keyword is used to explicitly throw an exception object in Java code?", ["throw", "throws", "raise", "fire"], 0),
                q("Which keyword is used in a method declaration header to declare exceptions it might throw?", ["throws", "throw", "exceptions", "warn"], 0),
                q("What exception is thrown when attempting to divide an integer by zero in Java?", ["ArithmeticException", "NullPointerException", "ZeroDivisionError", "NumberFormatException"], 0),
                q("What exception is thrown when calling a method on a variable that is null?", ["NullPointerException", "ArrayIndexOutOfBoundsException", "ArithmeticException", "IllegalArgumentException"], 0),
                q("What is the superclass of all exceptions and errors in Java?", ["Throwable", "Exception", "Error", "ObjectException"], 0),
            ],
            "5": [ # Java Hard Level 5 - Collections & ArrayList
                q("Which dynamically resizable collection class is part of java.util in Java?", ["ArrayList", "Array", "FixedList", "DynamicArray"], 0),
                q("How do you add an element to an ArrayList named list in Java?", ["list.add(item);", "list.push(item);", "list.append(item);", "list.insert(item);"], 0),
                q("How do you retrieve an element at index 2 from an ArrayList named list?", ["list.get(2)", "list[2]", "list.at(2)", "list(2)"], 0),
                q("How do you get the number of elements in an ArrayList in Java?", ["list.size()", "list.length()", "list.count()", "list.length"], 0),
                q("How do you remove an element at index 0 from an ArrayList in Java?", ["list.remove(0);", "list.delete(0);", "list.pop();", "list.drop(0);"], 0),
                q("Which wrapper class must be used for integers in an ArrayList (since primitives cannot be used directly)?", ["Integer (ArrayList<Integer>)", "int (ArrayList<int>)", "Number", "IntClass"], 0),
                q("Which method empties all elements from an ArrayList?", ["list.clear();", "list.empty();", "list.reset();", "list.removeAll();"], 0),
                q("Which method checks if an ArrayList contains a specific item and returns boolean?", ["list.contains(item)", "list.has(item)", "list.includes(item)", "list.exists(item)"], 0),
            ]
        }
    }
}

target_file = os.path.join("app", "src", "main", "assets", "questions.json")
with open(target_file, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"Successfully generated {target_file}")
total_q = sum(len(lvl_q) for lang in data.values() for diff in lang.values() for lvl_q in diff.values())
print(f"Total curated categorized questions: {total_q}")
